name: build-and-test

on:
  pull_request:
    branches: [main, release/**]
    types: [opened, reopened, synchronize, edited]
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.yml"
      - "**.yaml"
      - "**.json"

env:
  DOTNET_VERSION: "6.0.x" # The .NET SDK version to use

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ./Ashampoo-Translation-Systems.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-restore --verbosity normal
