name: prerelease-packages

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "::debug::${{ github.event.pull_request.merged }}"
          echo "::debug::${{ github.event.label.name }}"
  generate-version:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'site')) }}
    uses: ./.github/workflows/reuse-generate-version-and-init-release.yml
    with:
      prerelease: true
    secrets: inherit

  remove-prefix-from-version:
    needs: [ generate-version ]
    runs-on: ubuntu-latest
    steps:
      - name: remove-prefix
        id: remove-prefix
        run: |
          TAG=${{ needs.generate-version.outputs.version }}
          echo ::set-output name=version::${TAG#v}
    outputs: 
        version: ${{ steps.remove-prefix.outputs.version }}

  set-matrix:
    needs: [ generate-version ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set-matrix
        id: set-matrix
        run: echo "::set-output name=matrix::$(ls src/Ashampoo.Translation.Systems.*/src/Ashampoo.Translation.Systems.*.csproj | sed -r 's/.*\/(.*).csproj$/\1/')"
    outputs: 
        matrix: ${{ steps.set-matrix.outputs.matrix }}

  publish-nuget-packages:
    needs: [ generate-version, remove-prefix-from-version ,set-matrix ]
    strategy:
      matrix:
        project_name: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    uses: ./.github/workflows/reuse-publish-nuget-package.yml
    with:
      project_name: ${{ matrix.project_name }}
      version: ${{ needs.remove-prefix.outputs.version }}