name: prerelease-packages

on:
  push:
    branches: [main]

jobs: 
  release:
    uses: ./.github/workflows/reuse-generate-version-and-init-release.yml
    with: 
      prerelease: true
    secrets: inherit