name: release-packages

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  generate-version:
    if: ${{ (github.event.pull_request.merged == true) && ((contains(github.event.pull_request.labels.*.name, 'prerelease')) || (contains(github.event.pull_request.labels.*.name, 'release'))) }}
    uses: ./.github/workflows/reuse-generate-version-and-init-release.yml
    with:
      prerelease: ${{(contains(github.event.pull_request.labels.*.name, 'release')) == false}}
    secrets: inherit

  remove-prefix-from-version:
    needs: generate-version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.remove-prefix.outputs.version }}
    steps:
      - name: check-version
        run: |
          echo version: ${{ needs.generate-version.outputs.version }}
      - name: remove-prefix
        id: remove-prefix
        run: |
          TAG=${{ needs.generate-version.outputs.version }}
          echo ::set-output name=version::${TAG#v}
  
  publish-nuget-packages:
    needs: [ generate-version, remove-prefix-from-version ]
    uses: ./.github/workflows/reuse-publish-nuget-package.yml
    with:
      project_name: "Ashampoo.Translation.Systems.Formats"
      version: ${{ needs.remove-prefix-from-version.outputs.version }}
    secrets: inherit