name: release-abstraction-package

on:
  push:
    branches: [main]
#    paths:
#      - "src/Ashampoo.Translation.Systems.Formats.Abstractions/**"

jobs: 
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  release:
    uses: ./.github/workflows/reuse-generate-version.yml