name: reuse-generate-version
on:
  workflow_call:
    inputs:
      prerelease:
        description: 'indicates if the release is a prerelease'
        default: true
        required: true
        type: boolean
    outputs:
      abstract-version:
        description: "Version number of the abstraction package"
        value: ${{ jobs.bump-version.outputs.abstract-version }}
        
env:
  GITHUB_TOKEN: ${{ github.token }}
  MAJOR_PATTERN: "major"
  MINOR_PATTERN: "minor"
  BRANCH: "origin/main"
  STAGING_IDENTIFIER: "prerelease."
  
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set Staging identifier
      if: ${{ inputs.prerelease}}
      id: StagingIdentifier
      run: echo ::set-output name=tag::${{ env.STAGING_IDENTIFIER }}
        
    - name: Abstraction Prerelease Version
      if: ${{ inputs.prerelease}}
      id: AbstractPrereleaseVersion
      uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        change_path: "src/Ashampoo.Translation.Systems.Formats.Abstractions"
        tag_prefix: "abstract-v"
        major_pattern: ${{ env.MAJOR_PATTERN }}
        minor_pattern: ${{ env.MINOR_PATTERN }}
        format: "abstract-v${major}.${minor}.${patch}-${{ steps.StagingIdentifier.outputs.tag }}${increment}"
        version_format: "abstract-v${major}.${minor}.${patch}-${{ steps.StagingIdentifier.outputs.tag }}${increment}"
        bump_each_commit: false
        search_commit_body: true
    
    - name: Abstraction Release Version
      if: ${{ !inputs.prerelease}}
      id: AbstractReleaseVersion
      uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        change_path: "src/Ashampoo.Translation.Systems.Formats.Abstractions"
        tag_prefix: "abstract-v"
        major_pattern: ${{ env.MAJOR_PATTERN }}
        minor_pattern: ${{ env.MINOR_PATTERN }}
        format: "abstract-v${major}.${minor}.${patch}"
        version_format: "abstract-v${major}.${minor}.${patch}"
        bump_each_commit: false
        search_commit_body: true
        
    - name: Create Tag
      id: CreateTag
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git tag -a ${{ steps.AbstractPrereleaseVersion.outputs.version || steps.AbstractReleaseVersion.outputs.version }} -m "Generated by Action"
        git push --tags
      
    outputs:
      abstract-version: ${{ steps.AbstractPrereleaseVersion.outputs.version || steps.AbstractReleaseVersion.outputs.version }}
        