name: reuse-publish-nuget-package.yml

on: 
  workflow_call:
    inputs:
      project_name:
        description: "The name of the project to publish"
        required: true
        type: string
      version:
        description: "The version to publish"
        required: true
        type: string

env:
  DOTNET_VERSION: "6.0.x" # The .NET SDK version to use

jobs:     
  publish-nuget-package:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install dependencies
      run: dotnet restore ./src/${{ inputs.project_name }}/src/${{ inputs.project_name }}.csproj
      
    - name: Generate package
      run: dotnet pack ./src/${{ inputs.project_name }}/src/${{ inputs.project_name }}.csproj -c Release
      
    - name: Publish package
      run: |
        dotnet nuget push ./src/${{ inputs.project_name }}/src/bin/Release/${{ inputs.project_name }}.${{ inputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }}  --source https://api.nuget.org/v3/index.json