name: reuse-generate-version
on:
  workflow_call:
    outputs:
      abstract-version:
        description: "Version number of the abstraction package"
        value: ${{ jobs.bump-version.outputs.abstract-version }}
        
env:
  GITHUB_TOKEN: ${{ github.token }}
  MAJOR_PATTERN: "major"
  MINOR_PATTERN: "minor"
  BRANCH: "origin/main"
  
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Abstraction Version
      id: AbstractVersion
      uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        change_path: "src/Ashampoo.Translation.Systems.Formats.Abstractions"
        tag_prefix: "abstract-v"
        major_pattern: ${{ env.MAJOR_PATTERN }}
        minor_pattern: ${{ env.MINOR_PATTERN }}
        format: "abstract-v${major}.${minor}.${patch}-prerelease.${increment}"
        branch: ${{ env.BRANCH }}
        bump_each_commit: false
        search_commit_body: true
        
    - name: Create Tag
      id: CreateTag
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git tag -a ${{ steps.AbstractVersion.outputs.version }} -m "Generated by Action"
        git push --tags
      
    outputs:
      abstract-version: ${{ steps.AbstractVersion.outputs.version }}
        