name: reuse-generate-versions
on:
  workflow_call:
    inputs:
      prerelease:
        description: 'indicates if the release is a prerelease'
        default: true
        required: true
        type: boolean
    outputs:
      version:
        description: "Version number of the package"
        value: ${{ jobs.bump-version.outputs.version }}
        
env:
  GITHUB_TOKEN: ${{ github.token }}
  MAJOR_PATTERN: "major"
  MINOR_PATTERN: "minor"
  STAGING_IDENTIFIER: "prerelease."
  
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set Staging identifier
      if: ${{ inputs.prerelease}}
      id: StagingIdentifier
      run: echo ::set-output name=tag::${{ env.STAGING_IDENTIFIER }}
        
    - name: Prerelease Version
      if: ${{ inputs.prerelease}}
      id: PrereleaseVersion
      uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        tag_prefix: "v"
        major_pattern: ${{ env.MAJOR_PATTERN }}
        minor_pattern: ${{ env.MINOR_PATTERN }}
        format: "v${major}.${minor}.${patch}-${{ steps.StagingIdentifier.outputs.tag }}${increment}"
        version_format: "v${major}.${minor}.${patch}-${{ steps.StagingIdentifier.outputs.tag }}${increment}"
        bump_each_commit: false
        search_commit_body: true
    
    - name: Release Version
      if: ${{ !inputs.prerelease}}
      id: ReleaseVersion
      uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        tag_prefix: "v"
        major_pattern: ${{ env.MAJOR_PATTERN }}
        minor_pattern: ${{ env.MINOR_PATTERN }}
        format: "v${major}.${minor}.${patch}"
        version_format: "v${major}.${minor}.${patch}"
        bump_each_commit: false
        search_commit_body: true
        
    - name: Create Tag
      id: CreateTag
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git tag -a ${{ steps.PrereleaseVersion.outputs.version || steps.ReleaseVersion.outputs.version }} -m "Generated by Action"
        git push --tags
      
    outputs:
      version: ${{ steps.PrereleaseVersion.outputs.version || steps.ReleaseVersion.outputs.version }}
        